# This workflow will build the package, manually triggered

name: Package workflow


# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "package"
  package:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      # Get version from properties file
      - name: Read version from Properties file
        id: read_version
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: "publish.properties"
          property: "VERSION"

      # Create a full version number with the Run Number suffix
      - name: Create full version number
        uses: jwulf/add-env-vars-action@1.0
        with:
          map: '{"packageVersion": "${{ steps.read_version.outputs.value }}.${{ github.run_number }}"}'   
      
      - name: Show full version number
        run: echo ${{ env.packageVersion }}
