# This workflow will build the package, manually triggered

name: Package workflow


# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "package"
  package:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: master

      # Get version from properties file
      - name: Read value from Properties-file
        id: read_property
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './publish.properties'
          property: 'VERSION'
      - name: Do something with your bumped release version
        run: echo ${{ steps.read_property.outputs.value }}
        # will print "the value of 'the.key.of.the.property'"
